<a href="https://colab.research.google.com/github/AstridSerruto/Projects/blob/master/Predicting_football_matches(Web_crawling).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [60]:
import requests

import warnings
warnings.filterwarnings('ignore')

In [61]:
#Define url to scrape
standings_url = 'https://fbref.com/en/comps/9/Premier-League-Stats'

In [62]:
#Download the page by requesting the server
data = requests.get(standings_url)

In [63]:
from bs4 import BeautifulSoup

In [64]:
#Initalize using html
soup = BeautifulSoup(data.text)

In [65]:
#Obtain url for table 
standings_table = soup.select('table.stats_table')[0]

In [66]:
#Find all <a> tags inside table
links = standings_table.find_all('a')

In [67]:
#Get href for each link
links = [l.get('href') for l in links]

In [68]:
#Select the links with 'squads'
links = [l for l in links if '/squads/' in l]

In [69]:
#Convert links into full urls by adding string to begining of link
team_urls = [f'https://fbref.com{l}' for l in links]

In [70]:
team_urls

['https://fbref.com/en/squads/b8fd03ef/Manchester-City-Stats',
 'https://fbref.com/en/squads/822bd0ba/Liverpool-Stats',
 'https://fbref.com/en/squads/cff3d9bb/Chelsea-Stats',
 'https://fbref.com/en/squads/18bb7c10/Arsenal-Stats',
 'https://fbref.com/en/squads/361ca564/Tottenham-Hotspur-Stats',
 'https://fbref.com/en/squads/19538871/Manchester-United-Stats',
 'https://fbref.com/en/squads/7c21e445/West-Ham-United-Stats',
 'https://fbref.com/en/squads/8cec06e1/Wolverhampton-Wanderers-Stats',
 'https://fbref.com/en/squads/d07537b9/Brighton-and-Hove-Albion-Stats',
 'https://fbref.com/en/squads/b2b47a98/Newcastle-United-Stats',
 'https://fbref.com/en/squads/a2d435b3/Leicester-City-Stats',
 'https://fbref.com/en/squads/47c64c55/Crystal-Palace-Stats',
 'https://fbref.com/en/squads/8602292d/Aston-Villa-Stats',
 'https://fbref.com/en/squads/cd051869/Brentford-Stats',
 'https://fbref.com/en/squads/33c895d4/Southampton-Stats',
 'https://fbref.com/en/squads/943e8050/Burnley-Stats',
 'https://fbref.com/en/squads/5bfb9659/Leeds-United-Stats',
 'https://fbref.com/en/squads/d3fd31cc/Everton-Stats',
 'https://fbref.com/en/squads/2abfe087/Watford-Stats',
 'https://fbref.com/en/squads/1c781004/Norwich-City-Stats']

In [71]:
#Obtain stats from teams
team_url = team_urls[0]

In [72]:
#Get html of url
data = requests.get(team_url)

In [73]:
import pandas as pd

#Scan all tables on the page and look for 'Scores & Fixtures'
matches = pd.read_html(data.text, match='Scores & Fixtures')

In [74]:
#Look at data frame
matches[0].head()

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,xG,xGA,Poss,Attendance,Captain,Formation,Referee,Match Report,Notes
0,2021-08-07,17:15,Community Shield,FA Community Shield,Sat,Neutral,L,0,1,Leicester City,NaN,NaN,57.0,NaN,Fernandinho,4-3-3,Paul Tierney,Match Report,NaN
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0,1,Tottenham,1.9,1.3,64.0,58262.0,Fernandinho,4-3-3,Anthony Taylor,Match Report,NaN
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,Norwich City,2.7,0.1,67.0,51437.0,İlkay Gündoğan,4-3-3,Graham Scott,Match Report,NaN
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,Arsenal,3.8,0.1,80.0,52276.0,İlkay Gündoğan,4-3-3,Martin Atkinson,Match Report,NaN
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,Leicester City,2.9,0.8,61.0,32087.0,İlkay Gündoğan,4-3-3,Paul Tierney,Match Report,NaN

In [75]:
soup = BeautifulSoup(data.text)

In [76]:
#Find all <a> tags
links = soup.find_all('a')

In [77]:
#Use list comprehension to get url from link
links = [l.get('href') for l in links]

In [78]:
#Use list comprehension to find link to shooting stats
links = [l for l in links if l and 'all_comps/shooting/' in l]

In [79]:
#Add link to download data
data = requests.get(f'https://fbref.com{links[0]}')

In [80]:
#Create dataframe
shooting = pd.read_html(data.text, match='Shooting')[0]

shooting.head()

  For Manchester City                                                     \
                 Date   Time              Comp                Round  Day
0          2021-08-07  17:15  Community Shield  FA Community Shield  Sat
1          2021-08-15  16:30    Premier League          Matchweek 1  Sun
2          2021-08-21  15:00    Premier League          Matchweek 2  Sat
3          2021-08-28  12:30    Premier League          Matchweek 3  Sat
4          2021-09-11  15:00    Premier League          Matchweek 4  Sat

                                         ... Standard               Expected  \
     Venue Result GF GA        Opponent  ...     Dist   FK PK PKatt       xG
0  Neutral      L  0  1  Leicester City  ...      NaN  NaN  0     0      NaN
1     Away      L  0  1       Tottenham  ...     16.9  1.0  0     0      1.9
2     Home      W  5  0    Norwich City  ...     17.3  1.0  0     0      2.7
3     Home      W  5  0         Arsenal  ...     14.3  0.0  0     0      3.8
4     Away      W  1  0  Leicester City  ...     14.0  0.0  0     0      2.9

                            Unnamed: 25_level_0
  npxG npxG/Sh G-xG np:G-xG        Match Report
0  NaN     NaN  NaN     NaN        Match Report
1  1.9    0.11 -1.9    -1.9        Match Report
2  2.7    0.17  1.3     1.3        Match Report
3  3.8    0.15  1.2     1.2        Match Report
4  2.9    0.12 -1.9    -1.9        Match Report

[5 rows x 26 columns]

In [81]:
#Dataframe has multi level index, we will drop the top index. This will allows us to access each column individually
shooting.columns = shooting.columns.droplevel()

shooting.head()

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Dist,FK,PK,PKatt,xG,npxG,npxG/Sh,G-xG,np:G-xG,Match Report
0,2021-08-07,17:15,Community Shield,FA Community Shield,Sat,Neutral,L,0,1,Leicester City,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,Match Report
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0,1,Tottenham,...,16.9,1.0,0,0,1.9,1.9,0.11,-1.9,-1.9,Match Report
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,Norwich City,...,17.3,1.0,0,0,2.7,2.7,0.17,1.3,1.3,Match Report
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,Arsenal,...,14.3,0.0,0,0,3.8,3.8,0.15,1.2,1.2,Match Report
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,Leicester City,...,14.0,0.0,0,0,2.9,2.9,0.12,-1.9,-1.9,Match Report

In [82]:
#Merge both tables
team_data = matches[0].merge(shooting[['Date', 'Sh', 'SoT', 'Dist', 'FK', 'PK', 'PKatt']], on='Date')

team_data.head()

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Formation,Referee,Match Report,Notes,Sh,SoT,Dist,FK,PK,PKatt
0,2021-08-07,17:15,Community Shield,FA Community Shield,Sat,Neutral,L,0,1,Leicester City,...,4-3-3,Paul Tierney,Match Report,NaN,12,3,NaN,NaN,0,0
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0,1,Tottenham,...,4-3-3,Anthony Taylor,Match Report,NaN,18,4,16.9,1.0,0,0
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,Norwich City,...,4-3-3,Graham Scott,Match Report,NaN,16,4,17.3,1.0,0,0
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,Arsenal,...,4-3-3,Martin Atkinson,Match Report,NaN,25,10,14.3,0.0,0,0
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,Leicester City,...,4-3-3,Paul Tierney,Match Report,NaN,25,8,14.0,0.0,0,0

In [83]:
#Scraping data for multiple teams and multiple years.
years = list(range(2022, 2020, -1))

In [84]:
#Initialize list
all_matches = []

In [85]:
standings_url = 'https://fbref.com/en/comps/9/Premier-League-Stats'

In [86]:
import time
#Loop through each year
for year in years:
  data = requests.get(standings_url)   #Get html
  soup = BeautifulSoup(data.text)     #Parse html
  standings_table = soup.select('table.stats_table')[0]   #Look for table

  links = [l.get('href') for l in standings_table.find_all('a')]   #Find all team links
  links = [l for l in links if '/squads/' in l]   #Filter the links
  team_urls = [f'https://fbref.com{l}' for l in links]   #Change links to absolute
  
  previous_season = soup.select('a.prev')[0].get('href')
  standings_url = f'https://fbref.com/{previous_season}'

#Loop through each url
  for team_url in team_urls:
    team_name = team_url.split('/')[-1].replace('-Stats', '').replace('-', ' ')

    data = requests.get(team_url)   
    matches = pd.read_html(data.text, match='Scores & Fixtures')[0]

    soup = BeautifulSoup(data.text)
    links = [l.get('href') for l in soup.find_all('a')]
    links = [l for l in links if l and 'all_comps/shooting' in l]
    data = requests.get(f'https://fbref.com{links[0]}')
    shooting = pd.read_html(data.text, match='Shooting')[0]
    shooting.columns = shooting.columns.droplevel()

    try:
      team_data = matches.merge(shooting[['Date', 'Sh', 'SoT', 'Dist', 'FK', 'PK', 'PKatt']])
    except ValueError:   #To control missing values continue with loop
        continue

    team_data = team_data[team_data['Comp'] == 'Premier League'] #Filter the data
    team_data['Season'] = year   #Add Season and Team columns
    team_data['Team'] = team_name
    all_matches.append(team_data)   #Add Team data to list
    time.sleep(1) #Slow down scraping

In [87]:
#Combine individual frames into one.
match_df = pd.concat(all_matches)

match_df.head()

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Match Report,Notes,Sh,SoT,Dist,FK,PK,PKatt,Season,Team
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0,1,Tottenham,...,Match Report,NaN,18.0,4.0,16.9,1.0,0.0,0.0,2022,Manchester City
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5,0,Norwich City,...,Match Report,NaN,16.0,4.0,17.3,1.0,0.0,0.0,2022,Manchester City
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5,0,Arsenal,...,Match Report,NaN,25.0,10.0,14.3,0.0,0.0,0.0,2022,Manchester City
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1,0,Leicester City,...,Match Report,NaN,25.0,8.0,14.0,0.0,0.0,0.0,2022,Manchester City
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0,0,Southampton,...,Match Report,NaN,16.0,1.0,15.7,1.0,0.0,0.0,2022,Manchester City

In [88]:
#Convert all column names to lowercase
match_df.columns = [c.lower() for c in match_df.columns]

In [89]:
#Write all data to csv file
match_df.to_csv('matches.csv')